print('merhaba benim adım {}'.format("eren"))
print('merhaba benim adım {0},yasim {1}'.format("eren",21))
print('merhaba benim adım {1},yasim {0}'.format("eren",21))
print('merhaba benim adım {ad},yasim {yas}'.format(ad="eren",yas=21))
print('merhaba benim adım {0},yasim {1}'.format("eren",21))